from tkinter import *
def clicked1():
    txt.grid_remove()
    btn1.grid_remove()
    btn2.grid_remove()
    btn3.grid_remove()
    res = "Привет, {}".format(txt.get())
    lbl1.configure(text=res)
    lbl2.configure(text="Решаем линейное уравнение a*x+b=0, запишите коэффициенты")
    lbl2.grid(column=1, row=2)
    lbl3.configure(text="Коэффициент a")
    lbl3.grid(column=0, row=3)
    lbl4 = Label(window, text="Коэффициент b")
    lbl4.grid(column=0, row=4)
    txt1 = Entry(window, width=10)
    txt1.grid(column=1, row=3)
    txt2 = Entry(window, width=10)
    txt2.grid(column=1, row=4)
    btn4 = Button(window, text="Решить уравнение", command=clicked11)
    btn4.grid(column=1, row=8)
def clicked11():

    lbl2.configure(text="Ответ Х=")
    lbl2.grid(column=1, row=5)
def clicked2():
    btn1.config(state=DISABLED)
    btn2.config(state=DISABLED)
    btn3.config(state=DISABLED)
    lbl.configure(text="Решаем квадратное уравнение")
    lbl.grid(column=1, row=5)
def clicked3():
    btn1.config(state=DISABLED)
    btn2.config(state=DISABLED)
    btn3.config(state=DISABLED)
    lbl.configure(text="Решаем кубическое уравнение")
    lbl.grid(column=1, row=5)
window = Tk()
window.title("Добро пожаловать в приложение по решению уравнений")
window.geometry('800x500')
lbl1 = Label(window, text="Привет это приложение поможет решить тебе уравнение")
lbl1.grid(column=1, row=0)
lbl2 = Label(window, text="Как тебя зовут?")
lbl2.grid(column=0, row=1)
txt = Entry(window, width=10)
txt.grid(column=1, row=1)
lbl3 = Label(window, text="Какое уравнение ты хочешь решить?")
lbl3.grid(column=1, row=3)
btn1 = Button(window, text="Линейное уравнение", command=clicked1)
btn1.grid(column=0, row=4)
btn2 = Button(window, text="Квадратное уравнение", command=clicked2)
btn2.grid(column=1, row=4)
btn3 = Button(window, text="Кубическое уравнение", command=clicked3)
btn3.grid(column=2, row=4)
window.mainloop()


